/*
 * PROGRAMACION III - EXAMEN FINAL
 * MIÑO, GUILLE
 * INGENIERIA EN INFORMATICA - UAA
 * 3/08/2021
 */
package com.guilleminio.emails.vistas;

import com.guilleminio.emails.controladora.IniciarSesionControladora;
import com.guilleminio.emails.utilidades.Utilidades;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javafx.scene.input.KeyCode;
/**
 *
 * @author Guille
 */
public class frmIniciarSesion extends javax.swing.JFrame implements IVentana {

    private IniciarSesionControladora controladora;
    
    /**
     * Creates new form frmIniciarSesion
     */
    public frmIniciarSesion() {
        initComponents();
        
        inicializarVentana();
        
    }

    private void iniciarSesion(){
        if ( formularioCompleto()){

            String email = this.jTxEmail.getText();
            String contrasenia = String.valueOf(this.jPtxtContrasenia.getPassword());

            if ( this.controladora.iniciarSesion(email, contrasenia)){
                frmPrincipal vPrincipal = new frmPrincipal(this.controladora.obtenerIdUsuario());
                this.setVisible(false);
                vPrincipal.setVisible(true);
                this.dispose();
            }else{
                this.jLErrorDatosIncorrectos.setVisible(true);
            }
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jBtnCerrar = new javax.swing.JButton();
        jPanelSection = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBtnIniciarSesion = new javax.swing.JButton();
        jPtxtContrasenia = new javax.swing.JPasswordField();
        jLErrorEmail = new javax.swing.JLabel();
        jLErrorContrasenia = new javax.swing.JLabel();
        jLErrorDatosIncorrectos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jBtnCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 610));
        setName("frmIniciarSesion"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanelHeader.setBackground(new java.awt.Color(51, 153, 255));
        jPanelHeader.setMaximumSize(new java.awt.Dimension(480, 50));
        jPanelHeader.setMinimumSize(new java.awt.Dimension(480, 50));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(480, 50));
        jPanelHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        jBtnCerrar.setBackground(new java.awt.Color(51, 153, 255));
        jBtnCerrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guilleminio/emails/recursos/cerrar_celeste_30.jpg"))); // NOI18N
        jBtnCerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBtnCerrar.setBorderPainted(false);
        jBtnCerrar.setMaximumSize(new java.awt.Dimension(30, 30));
        jBtnCerrar.setMinimumSize(new java.awt.Dimension(30, 30));
        jBtnCerrar.setPreferredSize(new java.awt.Dimension(30, 30));
        jBtnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guilleminio/emails/recursos/cerrar_celeste_30_presionado.jpg"))); // NOI18N
        jBtnCerrar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guilleminio/emails/recursos/cerrar_celeste_30_presionado.jpg"))); // NOI18N
        jBtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarActionPerformed(evt);
            }
        });
        jPanelHeader.add(jBtnCerrar);

        getContentPane().add(jPanelHeader);

        jPanelSection.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSection.setMaximumSize(new java.awt.Dimension(480, 410));
        jPanelSection.setMinimumSize(new java.awt.Dimension(480, 410));
        jPanelSection.setPreferredSize(new java.awt.Dimension(480, 410));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("¡BIENVENID@!");
        jLabel1.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setMaximumSize(new java.awt.Dimension(370, 330));
        jPanel1.setMinimumSize(new java.awt.Dimension(370, 330));
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 330));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Email:");

        jTxEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTxEmail.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTxEmail.setMaximumSize(new java.awt.Dimension(340, 40));
        jTxEmail.setMinimumSize(new java.awt.Dimension(340, 40));
        jTxEmail.setPreferredSize(new java.awt.Dimension(340, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Contraseña:");

        jBtnIniciarSesion.setBackground(new java.awt.Color(51, 153, 255));
        jBtnIniciarSesion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBtnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIniciarSesion.setText("ACCEDER");
        jBtnIniciarSesion.setMaximumSize(new java.awt.Dimension(340, 50));
        jBtnIniciarSesion.setMinimumSize(new java.awt.Dimension(340, 50));
        jBtnIniciarSesion.setPreferredSize(new java.awt.Dimension(340, 50));
        jBtnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIniciarSesionActionPerformed(evt);
            }
        });
        jBtnIniciarSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnIniciarSesionKeyPressed(evt);
            }
        });

        jPtxtContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        jPtxtContrasenia.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPtxtContrasenia.setMaximumSize(new java.awt.Dimension(340, 40));
        jPtxtContrasenia.setMinimumSize(new java.awt.Dimension(340, 40));
        jPtxtContrasenia.setPreferredSize(new java.awt.Dimension(340, 40));

        jLErrorEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLErrorEmail.setForeground(new java.awt.Color(255, 0, 0));
        jLErrorEmail.setText("Debes indicar tu email");

        jLErrorContrasenia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLErrorContrasenia.setForeground(new java.awt.Color(255, 0, 0));
        jLErrorContrasenia.setText("Debes indicar tu contraseña");

        jLErrorDatosIncorrectos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLErrorDatosIncorrectos.setForeground(new java.awt.Color(255, 0, 0));
        jLErrorDatosIncorrectos.setText("Email y/o contraseña incorrectos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLErrorContrasenia))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jBtnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPtxtContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLErrorEmail))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLErrorDatosIncorrectos)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLErrorEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLErrorContrasenia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPtxtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLErrorDatosIncorrectos)
                .addGap(11, 11, 11)
                .addComponent(jBtnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelSectionLayout = new javax.swing.GroupLayout(jPanelSection);
        jPanelSection.setLayout(jPanelSectionLayout);
        jPanelSectionLayout.setHorizontalGroup(
            jPanelSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSectionLayout.createSequentialGroup()
                .addGroup(jPanelSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSectionLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1))
                    .addGroup(jPanelSectionLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanelSectionLayout.setVerticalGroup(
            jPanelSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSection);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(480, 150));
        jPanel2.setMinimumSize(new java.awt.Dimension(480, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(480, 150));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("¿No tenés una cuenta aún?");

        jBtnCrearCuenta.setBackground(new java.awt.Color(51, 153, 255));
        jBtnCrearCuenta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBtnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCrearCuenta.setText("CREAR CUENTA");
        jBtnCrearCuenta.setMaximumSize(new java.awt.Dimension(340, 50));
        jBtnCrearCuenta.setMinimumSize(new java.awt.Dimension(340, 50));
        jBtnCrearCuenta.setPreferredSize(new java.awt.Dimension(340, 50));
        jBtnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jBtnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jBtnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(0);
        
    }//GEN-LAST:event_jBtnCerrarActionPerformed

    private void jBtnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIniciarSesionActionPerformed
        // TODO add your handling code here:
        iniciarSesion();
    }//GEN-LAST:event_jBtnIniciarSesionActionPerformed

    private void jBtnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearCuentaActionPerformed
        // TODO add your handling code here:
        abrirVentana();
    }//GEN-LAST:event_jBtnCrearCuentaActionPerformed

    private void jBtnIniciarSesionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnIniciarSesionKeyPressed
        // TODO add your handling code here:
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
            iniciarSesion();
    }//GEN-LAST:event_jBtnIniciarSesionKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnCrearCuenta;
    private javax.swing.JButton jBtnIniciarSesion;
    private javax.swing.JLabel jLErrorContrasenia;
    private javax.swing.JLabel jLErrorDatosIncorrectos;
    private javax.swing.JLabel jLErrorEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSection;
    private javax.swing.JPasswordField jPtxtContrasenia;
    private javax.swing.JTextField jTxEmail;
    // End of variables declaration//GEN-END:variables

    @Override
    public void inicializarVentana() {
        this.setLocationRelativeTo(this);
        this.controladora = new IniciarSesionControladora();
        limpiarErrores();
        
    }

    @Override
    public boolean formularioCompleto() {
    
        limpiarErrores();
        
        String email = this.jTxEmail.getText();
       
        if ( email.equals("")){
            this.jLErrorEmail.setVisible(true);
            return false;
        }
        
        if ( !Utilidades.validarFormatoEmail(email) ){
            this.jLErrorEmail.setText("El formato del email no es correcto.");
            this.jLErrorEmail.setVisible(true);
            return false;
        }
        
        if ( this.jPtxtContrasenia.getPassword().length == 0){
            this.jLErrorContrasenia.setVisible(true);
            return false;
        }
        return true;
    }

    @Override
    public void abrirVentana() {
    
        frmRegistroPaso1 vRegistro = new frmRegistroPaso1();
        this.setVisible(false);
        vRegistro.setVisible(true);
        this.dispose();
    }

    @Override
    public void limpiarErrores() {
        this.jLErrorEmail.setText("Debes indicar tu email.");
        this.jLErrorEmail.setVisible(false);
        this.jLErrorContrasenia.setVisible(false);
        this.jLErrorDatosIncorrectos.setVisible(false);
    }
}
