/*
 * PROGRAMACION III - EXAMEN FINAL
 * MIÑO, GUILLE
 * INGENIERIA EN INFORMATICA - UAA
 * 3/08/2021
 */
package com.guilleminio.emails.vistas;

import com.guilleminio.emails.controladora.CrearCuentaControladora;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Guille
 */
public class frmRegistroPaso1 extends javax.swing.JFrame implements IVentana {

    private CrearCuentaControladora controladora;
    
    /**
     * Creates new form frmRegistro
     */
    public frmRegistroPaso1() {
        initComponents();
        
        inicializarVentana();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        lbErrorNombre = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextApellido = new javax.swing.JTextField();
        lbErrorApellido = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabelEmailDominio = new javax.swing.JLabel();
        lbErrorEmail = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextContrasenia = new javax.swing.JPasswordField();
        lbErrorContrasenia = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextRepetirContrasenia = new javax.swing.JPasswordField();
        lbErrorRepetirContrasenia = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 640));
        setName("Registro_paso_1"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(960, 80));
        jPanel3.setMinimumSize(new java.awt.Dimension(960, 80));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREAR CUENTA");
        jLabel1.setMaximumSize(new java.awt.Dimension(287, 70));
        jLabel1.setMinimumSize(new java.awt.Dimension(287, 70));
        jLabel1.setPreferredSize(new java.awt.Dimension(287, 70));
        jPanel3.add(jLabel1);

        getContentPane().add(jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 480));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 480));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comencemos con algunos datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(840, 400));
        jPanel4.setMinimumSize(new java.awt.Dimension(840, 400));
        jPanel4.setPreferredSize(new java.awt.Dimension(840, 400));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel7.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Nombre:");
        jLabel2.setMaximumSize(new java.awt.Dimension(350, 24));
        jLabel2.setMinimumSize(new java.awt.Dimension(350, 24));
        jLabel2.setPreferredSize(new java.awt.Dimension(350, 24));
        jPanel7.add(jLabel2);

        jTextNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextNombre.setMaximumSize(new java.awt.Dimension(350, 30));
        jTextNombre.setMinimumSize(new java.awt.Dimension(350, 30));
        jTextNombre.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel7.add(jTextNombre);

        lbErrorNombre.setForeground(new java.awt.Color(255, 0, 0));
        lbErrorNombre.setText("Tenés que indicar un nombre");
        lbErrorNombre.setMaximumSize(new java.awt.Dimension(350, 16));
        lbErrorNombre.setMinimumSize(new java.awt.Dimension(350, 16));
        lbErrorNombre.setPreferredSize(new java.awt.Dimension(350, 16));
        jPanel7.add(lbErrorNombre);

        jPanel4.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel8.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel8.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Apellido:");
        jLabel3.setMaximumSize(new java.awt.Dimension(350, 24));
        jLabel3.setMinimumSize(new java.awt.Dimension(350, 24));
        jLabel3.setPreferredSize(new java.awt.Dimension(350, 24));
        jPanel8.add(jLabel3);

        jTextApellido.setBackground(new java.awt.Color(255, 255, 255));
        jTextApellido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextApellido.setMaximumSize(new java.awt.Dimension(350, 30));
        jTextApellido.setMinimumSize(new java.awt.Dimension(350, 30));
        jTextApellido.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel8.add(jTextApellido);

        lbErrorApellido.setForeground(new java.awt.Color(255, 0, 0));
        lbErrorApellido.setText("Tenés que indicar un apellido");
        lbErrorApellido.setMaximumSize(new java.awt.Dimension(350, 16));
        lbErrorApellido.setMinimumSize(new java.awt.Dimension(350, 16));
        lbErrorApellido.setPreferredSize(new java.awt.Dimension(350, 16));
        jPanel8.add(lbErrorApellido);

        jPanel4.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setMaximumSize(new java.awt.Dimension(805, 100));
        jPanel9.setMinimumSize(new java.awt.Dimension(805, 100));
        jPanel9.setPreferredSize(new java.awt.Dimension(805, 100));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 25, 5));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Email:");
        jLabel4.setMaximumSize(new java.awt.Dimension(805, 24));
        jLabel4.setMinimumSize(new java.awt.Dimension(805, 24));
        jLabel4.setPreferredSize(new java.awt.Dimension(805, 24));
        jPanel9.add(jLabel4);

        jTextEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTextEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextEmail.setMaximumSize(new java.awt.Dimension(350, 30));
        jTextEmail.setMinimumSize(new java.awt.Dimension(350, 30));
        jTextEmail.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel9.add(jTextEmail);

        jLabelEmailDominio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelEmailDominio.setForeground(new java.awt.Color(153, 153, 153));
        jLabelEmailDominio.setText("@myemail.com");
        jPanel9.add(jLabelEmailDominio);

        lbErrorEmail.setForeground(new java.awt.Color(255, 0, 0));
        lbErrorEmail.setText("Tenés que indicar un email");
        lbErrorEmail.setMaximumSize(new java.awt.Dimension(750, 16));
        lbErrorEmail.setMinimumSize(new java.awt.Dimension(750, 16));
        lbErrorEmail.setPreferredSize(new java.awt.Dimension(750, 16));
        jPanel9.add(lbErrorEmail);

        jPanel4.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel10.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel10.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Contraseña:");
        jLabel7.setMaximumSize(new java.awt.Dimension(350, 24));
        jLabel7.setMinimumSize(new java.awt.Dimension(350, 24));
        jLabel7.setPreferredSize(new java.awt.Dimension(350, 24));
        jPanel10.add(jLabel7);

        jTextContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        jTextContrasenia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextContrasenia.setMaximumSize(new java.awt.Dimension(350, 30));
        jTextContrasenia.setMinimumSize(new java.awt.Dimension(350, 30));
        jTextContrasenia.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel10.add(jTextContrasenia);

        lbErrorContrasenia.setForeground(new java.awt.Color(255, 0, 0));
        lbErrorContrasenia.setText("Tenés que indicar una contraseña");
        lbErrorContrasenia.setMaximumSize(new java.awt.Dimension(350, 16));
        lbErrorContrasenia.setMinimumSize(new java.awt.Dimension(350, 16));
        lbErrorContrasenia.setPreferredSize(new java.awt.Dimension(350, 16));
        jPanel10.add(lbErrorContrasenia);

        jPanel4.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel11.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel11.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Repetir contraseña:");
        jLabel8.setMaximumSize(new java.awt.Dimension(350, 24));
        jLabel8.setMinimumSize(new java.awt.Dimension(350, 24));
        jLabel8.setPreferredSize(new java.awt.Dimension(350, 24));
        jPanel11.add(jLabel8);

        jTextRepetirContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        jTextRepetirContrasenia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextRepetirContrasenia.setMaximumSize(new java.awt.Dimension(350, 30));
        jTextRepetirContrasenia.setMinimumSize(new java.awt.Dimension(350, 30));
        jTextRepetirContrasenia.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel11.add(jTextRepetirContrasenia);

        lbErrorRepetirContrasenia.setForeground(new java.awt.Color(255, 0, 0));
        lbErrorRepetirContrasenia.setText("jLabel13");
        lbErrorRepetirContrasenia.setMaximumSize(new java.awt.Dimension(350, 16));
        lbErrorRepetirContrasenia.setMinimumSize(new java.awt.Dimension(350, 16));
        lbErrorRepetirContrasenia.setPreferredSize(new java.awt.Dimension(350, 16));
        jPanel11.add(lbErrorRepetirContrasenia);

        jPanel4.add(jPanel11);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Los campos son obligatorios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(365, 365, 365))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setMaximumSize(new java.awt.Dimension(960, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(960, 80));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(480, 80));
        jPanel5.setMinimumSize(new java.awt.Dimension(480, 80));
        jPanel5.setPreferredSize(new java.awt.Dimension(480, 80));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(51, 153, 255));
        btnVolver.setText("VOLVER");
        btnVolver.setBorderPainted(false);
        btnVolver.setFocusPainted(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel5.add(btnVolver);

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(480, 80));
        jPanel6.setMinimumSize(new java.awt.Dimension(480, 80));
        jPanel6.setPreferredSize(new java.awt.Dimension(480, 80));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        btnContinuar.setBackground(new java.awt.Color(51, 153, 255));
        btnContinuar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("CONTINUAR");
        btnContinuar.setBorderPainted(false);
        btnContinuar.setFocusPainted(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel6.add(btnContinuar);

        jPanel2.add(jPanel6);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean formularioCompleto(){
        
        limpiarErrores();
        
        if ( this.jTextNombre.getText().equals("")){
            this.lbErrorNombre.setVisible(true);
            return false;
        }
        
        if ( this.jTextApellido.getText().equals("")){
            this.lbErrorApellido.setVisible(true);
            return false;
        }
        
        if ( this.jTextEmail.getText().equals("")){
            this.lbErrorEmail.setVisible(true);
            return false;
        }
        
        String email = this.jTextEmail.getText() +  this.jLabelEmailDominio.getText();
        if ( this.controladora.existeUsuario(email)){
            this.lbErrorEmail.setVisible(true);
            this.lbErrorEmail.setText("La dirección de email ya existe");
            return false;
        }
        
        if ( this.jTextContrasenia.getPassword().length == 0){
            this.lbErrorContrasenia.setVisible(true);
            return false;
        }
        
        if ( this.jTextRepetirContrasenia.getPassword().length == 0){
            this.lbErrorRepetirContrasenia.setVisible(true);
            this.lbErrorRepetirContrasenia.setText("Debes confirmar la contraseña");
            return false;
        }
        
        if ( !String.valueOf(this.jTextContrasenia.getPassword()).equals(String.valueOf(this.jTextRepetirContrasenia.getPassword()))){
            this.lbErrorRepetirContrasenia.setText("Las contraseñas no coinciden");
            this.lbErrorRepetirContrasenia.setVisible(true);
            return false;
        }
        
        return true;
    }
    
    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        
        if ( formularioCompleto()){
            
            Date hoy = new Date();
            Calendar calendario = Calendar.getInstance();
            calendario.setTime(hoy);
            
            if ( this.controladora.agregarUsuario(this.jTextNombre.getText(),this.jTextApellido.getText(), this.jTextEmail.getText()+ this.jLabelEmailDominio.getText(), String.valueOf(this.jTextContrasenia.getPassword()), calendario.getTime())){
           
                abrirVentana();
            }
            
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro no querés continuar con la creación de tu cuenta?","Atención!",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        
        if ( opcion == JOptionPane.YES_OPTION){
            frmIniciarSesion vIniciarSesion = new frmIniciarSesion();
            this.setVisible(false);
            vIniciarSesion.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPaso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPaso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPaso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPaso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroPaso1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEmailDominio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JPasswordField jTextContrasenia;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JPasswordField jTextRepetirContrasenia;
    private javax.swing.JLabel lbErrorApellido;
    private javax.swing.JLabel lbErrorContrasenia;
    private javax.swing.JLabel lbErrorEmail;
    private javax.swing.JLabel lbErrorNombre;
    private javax.swing.JLabel lbErrorRepetirContrasenia;
    // End of variables declaration//GEN-END:variables

    @Override
    public void inicializarVentana() {
    
        this.setLocationRelativeTo(this);
        this.controladora = new CrearCuentaControladora();
        limpiarErrores();
    }

    @Override
    public void abrirVentana() {
        
        frmRegistroPaso2 vRegistroPaso2 = new frmRegistroPaso2();
        this.setVisible(false);
        vRegistroPaso2.setVisible(true);
        this.dispose();
        
    }

    @Override
    public void limpiarErrores() {
    
        this.lbErrorNombre.setVisible(false);
        this.lbErrorApellido.setVisible(false);
        this.lbErrorEmail.setVisible(false);
        this.lbErrorContrasenia.setVisible(false);
        this.lbErrorRepetirContrasenia.setVisible(false);
        
        this.lbErrorEmail.setText("Tenés que indicar un email");
     
    }

}
