/*
 * PROGRAMACION III - EXAMEN FINAL
 * MIÑO, GUILLE
 * INGENIERIA EN INFORMATICA - UAA
 * 3/08/2021
 */
package com.guilleminio.emails.vistas;

import com.guilleminio.emails.controladora.CrearCuentaControladora;
import com.guilleminio.emails.utilidades.Utilidades;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Guille
 */
public class frmRegistroPaso2 extends javax.swing.JFrame implements IVentana{

    JFileChooser jImgFileChooser;
    
    byte[] imagenGuardar;
    FileInputStream streamIn;
    FileOutputStream streamOut;
    
    Icon imagenPorDefecto;
    
    CrearCuentaControladora controladora;
    int idUsuario;
    
    /**
     * Creates new form frmRegistroPaso2
     */
    public frmRegistroPaso2() {
        initComponents();
        
        inicializarVentana();
        
    }

    /*------------------------------------------------*/
    //             PROCESAMIENTO DE IMAGEN            //  
    private void cargarImagenDefault(){
        
        ImageIcon imagen_perfil = new ImageIcon("res\\imagenes_usuarios\\user_default.jpg");
        
        this.imagenPorDefecto = new ImageIcon(imagen_perfil.getImage().getScaledInstance(this.jLImagen.getPreferredSize().width, this.jLImagen.getPreferredSize().width, Image.SCALE_DEFAULT));
        this.jLImagen.setText("");
        this.jLImagen.setIcon(this.imagenPorDefecto);
    }
    
    private String guardarImagenUsuario( File aImage ){
        
        String res = null;
        
        try{
            this.streamOut = new FileOutputStream( aImage );
            this.streamOut.write(this.imagenGuardar);
            res = "Foto guardada";
        }catch (Exception e){
            System.out.println(e.toString());
        }
        
        return res;
    }
    
    
    private String generarImagenUsuario(){
        
        String urlPath = null;
        
        if ( this.jImgFileChooser != null ){
            
            File imagen = this.jImgFileChooser.getSelectedFile();
            
            try
            {
                BufferedImage originalImage = ImageIO.read(imagen);
            
                urlPath = Utilidades.DEFAULT_PATH_USER_PROFILE + this.idUsuario + Utilidades.DEFAULT_IMAGE_EXTENSION;
            
                ImageIO.write(originalImage, "jpg", new File(urlPath));
                return urlPath;
            } 
            catch (IOException e ) 
            {
                e.printStackTrace();
            }
           
       }
       
       return null;
    }
    
    //      FIN PROCESAMIENTO DE IMAGEN                //
    /*------------------------------------------------*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLImagen = new javax.swing.JLabel();
        jBtnAgregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jBtnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 640));
        setName("frmRegistroPaso2"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 80));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("YA FALTA POCO...");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(960, 480));
        jPanel2.setMinimumSize(new java.awt.Dimension(960, 480));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("¿Querés agregar una foto a tu perfil?");

        jLImagen.setBackground(new java.awt.Color(153, 153, 153));
        jLImagen.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImagen.setText("IMAGEN");
        jLImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLImagen.setMaximumSize(new java.awt.Dimension(300, 300));
        jLImagen.setMinimumSize(new java.awt.Dimension(300, 300));
        jLImagen.setOpaque(true);
        jLImagen.setPreferredSize(new java.awt.Dimension(300, 300));

        jBtnAgregar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBtnAgregar.setText("AGREGAR");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAgregar)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAgregar))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(960, 80));
        jPanel3.setMinimumSize(new java.awt.Dimension(960, 80));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(480, 80));
        jPanel4.setMinimumSize(new java.awt.Dimension(480, 80));
        jPanel4.setPreferredSize(new java.awt.Dimension(480, 80));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));
        jPanel3.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(480, 80));
        jPanel5.setMinimumSize(new java.awt.Dimension(480, 80));
        jPanel5.setPreferredSize(new java.awt.Dimension(480, 80));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        jBtnContinuar.setBackground(new java.awt.Color(51, 153, 255));
        jBtnContinuar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBtnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnContinuar.setText("CONTINUAR");
        jBtnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnContinuarActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnContinuar);

        jPanel3.add(jPanel5);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("JPG","jpg");
        
        jImgFileChooser = new JFileChooser("res\\imagenes_usuarios\\para_agregar");
        jImgFileChooser.setDialogTitle("Elige una imagen");
        jImgFileChooser.setFileFilter(imageFilter);
        
        if ( jImgFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
        
                File archivoImagen = jImgFileChooser.getSelectedFile();

            try{

                ImageIcon icon = new ImageIcon(archivoImagen.toString());
                System.out.println(archivoImagen.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(this.jLImagen.getPreferredSize().width, this.jLImagen.getPreferredSize().height, Image.SCALE_DEFAULT));

                this.jLImagen.setIcon( icono );

            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen "+ ex);     
            }
        }
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnContinuarActionPerformed
        // TODO add your handling code here:
        
        if ( this.imagenPorDefecto.equals(this.jLImagen.getIcon())){
            
            int opcionElegida = JOptionPane.showConfirmDialog(this,"¿Seguro no deseas agregar una imagen?","Atención!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
            if ( opcionElegida == JOptionPane.YES_OPTION){
                
                int opcion = JOptionPane.showConfirmDialog(this, "Ya eres miembr@ de myemai.com","¡GENIAL!",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE);
            
                if ( opcion == JOptionPane.YES_OPTION ){
                    
                    abrirVentana();
                }
            }
        }
        else{
            String rutaImagenUsuario = generarImagenUsuario();
            
            if ( this.controladora.agregarImagenUsuario(this.idUsuario, rutaImagenUsuario)){
            
                int opcion = JOptionPane.showConfirmDialog(this, "Ya eres miembr@ de myemai.com","¡GENIAL!",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE);
            
                if ( opcion == JOptionPane.YES_OPTION ){
                    
                    abrirVentana();
                }
            }
        
        }
       
    }//GEN-LAST:event_jBtnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPaso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPaso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPaso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPaso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroPaso2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnContinuar;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void inicializarVentana() {
        this.setLocationRelativeTo(this);
        cargarImagenDefault();
        this.controladora = new CrearCuentaControladora();
        this.idUsuario = this.controladora.obtenerUltimoUsuarioAgregado();

    }

    @Override
    public boolean formularioCompleto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void abrirVentana() {
        frmPrincipal vPrincipal = new frmPrincipal(this.idUsuario);
        vPrincipal.setVisible(true);
        this.dispose();
    }

    @Override
    public void limpiarErrores() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
