package com.guilleminio.emails.modelos;
// Generated 01-ago-2021 6:53:46 by Hibernate Tools 4.3.1



/**
 * Contactos generated by hbm2java
 */
public class Contactos  implements java.io.Serializable {


     private Integer idContacto;
     private Usuarios usuarios;
     private String nombreContacto;
     private String apellidoContacto;
     private String emailContacto;
     private String imagenContacto;

    public Contactos() {
    }

    public Contactos(Usuarios usuarios, String nombreContacto, String apellidoContacto, String emailContacto, String imagenContacto) {
       this.usuarios = usuarios;
       this.nombreContacto = nombreContacto;
       this.apellidoContacto = apellidoContacto;
       this.emailContacto = emailContacto;
       this.imagenContacto = imagenContacto;
    }
    
    public Contactos(Usuarios usuarios, String nombreContacto, String apellidoContacto, String emailContacto) {
       this.usuarios = usuarios;
       this.nombreContacto = nombreContacto;
       this.apellidoContacto = apellidoContacto;
       this.emailContacto = emailContacto;
    }
    
    public Integer getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(Integer idContacto) {
        this.idContacto = idContacto;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }
    public String getApellidoContacto() {
        return this.apellidoContacto;
    }
    
    public void setApellidoContacto(String apellidoContacto) {
        this.apellidoContacto = apellidoContacto;
    }
    public String getEmailContacto() {
        return this.emailContacto;
    }
    
    public void setEmailContacto(String emailContacto) {
        this.emailContacto = emailContacto;
    }
    public String getImagenContacto() {
        return this.imagenContacto;
    }
    
    public void setImagenContacto(String imagenContacto) {
        this.imagenContacto = imagenContacto;
    }




}


