package com.guilleminio.emails.modelos;
// Generated 01-ago-2021 6:53:46 by Hibernate Tools 4.3.1



/**
 * RespuestasPorEmailId generated by hbm2java
 */
public class RespuestasPorEmailId  implements java.io.Serializable {


     private int idRespuesta;
     private int idEmailRespuesta;

    public RespuestasPorEmailId() {
    }

    public RespuestasPorEmailId(int idRespuesta, int idEmailRespuesta) {
       this.idRespuesta = idRespuesta;
       this.idEmailRespuesta = idEmailRespuesta;
    }
   
    public int getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(int idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public int getIdEmailRespuesta() {
        return this.idEmailRespuesta;
    }
    
    public void setIdEmailRespuesta(int idEmailRespuesta) {
        this.idEmailRespuesta = idEmailRespuesta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RespuestasPorEmailId) ) return false;
		 RespuestasPorEmailId castOther = ( RespuestasPorEmailId ) other; 
         
		 return (this.getIdRespuesta()==castOther.getIdRespuesta())
 && (this.getIdEmailRespuesta()==castOther.getIdEmailRespuesta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRespuesta();
         result = 37 * result + this.getIdEmailRespuesta();
         return result;
   }   


}


