package com.guilleminio.emails.modelos;
// Generated 01-ago-2021 6:53:46 by Hibernate Tools 4.3.1



/**
 * RespuestasPorEmail generated by hbm2java
 */
public class RespuestasPorEmail  implements java.io.Serializable {


     private RespuestasPorEmailId id;
     private Emails emailsByIdEmailRespuesta;
     private Emails emailsByIdEmailOrigen;

    public RespuestasPorEmail() {
    }

    public RespuestasPorEmail(RespuestasPorEmailId id, Emails emailsByIdEmailRespuesta, Emails emailsByIdEmailOrigen) {
       this.id = id;
       this.emailsByIdEmailRespuesta = emailsByIdEmailRespuesta;
       this.emailsByIdEmailOrigen = emailsByIdEmailOrigen;
    }
   
    public RespuestasPorEmailId getId() {
        return this.id;
    }
    
    public void setId(RespuestasPorEmailId id) {
        this.id = id;
    }
    public Emails getEmailsByIdEmailRespuesta() {
        return this.emailsByIdEmailRespuesta;
    }
    
    public void setEmailsByIdEmailRespuesta(Emails emailsByIdEmailRespuesta) {
        this.emailsByIdEmailRespuesta = emailsByIdEmailRespuesta;
    }
    public Emails getEmailsByIdEmailOrigen() {
        return this.emailsByIdEmailOrigen;
    }
    
    public void setEmailsByIdEmailOrigen(Emails emailsByIdEmailOrigen) {
        this.emailsByIdEmailOrigen = emailsByIdEmailOrigen;
    }




}


