package com.guilleminio.emails.modelos;
// Generated 01-ago-2021 6:53:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombreUsuario;
     private String apellidoUsuario;
     private String emailUsuario;
     private String contraseniaUsuario;
     private Date fechaAltaUsuario;
     private String imagenPathUsuario;
     private Set contactoses = new HashSet(0);
     private Set emailses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String nombreUsuario, String apellidoUsuario, String emailUsuario, String contraseniaUsuario, Date fechaAltaUsuario) {
        this.nombreUsuario = nombreUsuario;
        this.apellidoUsuario = apellidoUsuario;
        this.emailUsuario = emailUsuario;
        this.contraseniaUsuario = contraseniaUsuario;
        this.fechaAltaUsuario = fechaAltaUsuario;
    }
    public Usuarios(String nombreUsuario, String apellidoUsuario, String emailUsuario, String contraseniaUsuario, Date fechaAltaUsuario, String imagenPathUsuario, Set contactoses, Set emailses) {
       this.nombreUsuario = nombreUsuario;
       this.apellidoUsuario = apellidoUsuario;
       this.emailUsuario = emailUsuario;
       this.contraseniaUsuario = contraseniaUsuario;
       this.fechaAltaUsuario = fechaAltaUsuario;
       this.imagenPathUsuario = imagenPathUsuario;
       this.contactoses = contactoses;
       this.emailses = emailses;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getApellidoUsuario() {
        return this.apellidoUsuario;
    }
    
    public void setApellidoUsuario(String apellidoUsuario) {
        this.apellidoUsuario = apellidoUsuario;
    }
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public String getContraseniaUsuario() {
        return this.contraseniaUsuario;
    }
    
    public void setContraseniaUsuario(String contraseniaUsuario) {
        this.contraseniaUsuario = contraseniaUsuario;
    }
    public Date getFechaAltaUsuario() {
        return this.fechaAltaUsuario;
    }
    
    public void setFechaAltaUsuario(Date fechaAltaUsuario) {
        this.fechaAltaUsuario = fechaAltaUsuario;
    }
    public String getImagenPathUsuario() {
        return this.imagenPathUsuario;
    }
    
    public void setImagenPathUsuario(String imagenPathUsuario) {
        this.imagenPathUsuario = imagenPathUsuario;
    }
    public Set getContactoses() {
        return this.contactoses;
    }
    
    public void setContactoses(Set contactoses) {
        this.contactoses = contactoses;
    }
    public Set getEmailses() {
        return this.emailses;
    }
    
    public void setEmailses(Set emailses) {
        this.emailses = emailses;
    }




}


